### ISSUE TITLE
[BUG] PDFs with equiptment comments not generating

### ISSUE THREAD

**Issue by Jbithell** [adam-rms/adam-rms#491]
### Have you contacted the support team about this?

No - I'm an experienced maintainer and I've found/suspect I've found root cause

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v1.106.0

### Current Behavior

Generating a PDF with the "equiptment comments" box checked causes a javascript error

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '_calcWidth')
    at layoutBuilder.js:525:26
    at TraversalTracker.auto (traversalTracker.js:43:2)
    at LayoutBuilder.processRow (layoutBuilder.js:518:15)
    at LayoutBuilder.processTable (layoutBuilder.js:653:21)
    at layoutBuilder.js:401:9
    at applyMargins (layoutBuilder.js:449:3)
    at LayoutBuilder.processNode (layoutBuilder.js:374:2)
    at layoutBuilder.js:476:8
    at Array.forEach (<anonymous>)
    at LayoutBuilder.processVerticalContainer (layoutBuilder.js:475:13)
```

### Expected Behavior

Should render the PDF

### Steps To Reproduce

![image](https://github.com/adam-rms/adam-rms/assets/8408967/d767551a-ce12-419b-8e6d-1dc636e716a0)

**Comment by Jbithell** [comment]
These seem to be working fine
